ebs-prbs: prbs/asg.h File Reference
asg.h File Reference
Interface and usage of the alternating step prbs generator.
#include "lfsr.h"
Data Structures
struct ASG_LFSR16_t
16 bit LFSR based Alternating Step Generator
struct ASG_LFSR32_t
32 bit LFSR based Alternating Step Generator
struct ASG_LFSR64_t
64 bit LFSR based Alternating Step Generator
Typedefs
Alternating Step Generator Typedefs
These types contain the core of Alternating Step Generators. Each is composed of three LFSRs of appropriate sizes.
Values in the struct should not be used directly. The functions listed in the interface can be used to operate on the ASG.
typedef struct ASG_LFSR16_t asg_lfsr16_t
16 bit LFSR based Alternating Step Generator
typedef struct ASG_LFSR32_t asg_lfsr32_t
32 bit LFSR based Alternating Step Generator
typedef struct ASG_LFSR64_t asg_lfsr64_t
64 bit LFSR based Alternating Step Generator
Functions
Alternating Step Generator Initialization Functions
Intialize the alternating step generator's LFSRs with the default seed. These functions are superceded by the AddEntropy functions, and is retained here for backwards compatibility.
Applications should avoid using these.
void asg_lfsr16_vInit (asg_lfsr16_t *asg)
Initialize a asg_lfsr16_t structure using the default seeds.
void asg_lfsr32_vInit (asg_lfsr32_t *asg)
Initialize a asg_lfsr32_t structure using the default seeds.
void asg_lfsr64_vInit (asg_lfsr64_t *asg)
Initialize a asg_lfsr64_t structure using the default seeds.
Alternating Step Generator Add Entropy Functions
Add entropy to the alternating step gnerator. These functions simply replace the contained LFSRs with the provided entropy bytes. With the deprecation of the ASG Initialization functions, applications must call this function and provide some entropy before the SG is usable.
If randomness is required, entropy should come from a random source. If determinism is required, the default seed or another predetermined constant may be used.
void asg_lfsr16_vAddEntropy (asg_lfsr16_t *asg, void *entropy)
Add entropy to a asg_lfsr16_t structure.
void asg_lfsr32_vAddEntropy (asg_lfsr32_t *asg, void *entropy)
Add entropy to a asg_lfsr32_t structure.
void asg_lfsr64_vAddEntropy (asg_lfsr64_t *asg, void *entropy)
Add entropy to a asg_lfsr64_t structure.
Alternating Step Generator Get Next Byte Functions
Get the next byte in the Alternating Step Generator's pseudo random binary sequence. This function constructs the byte by repeatedly calling the bit generation functions.
uint8_t asg_lfsr16_cGetNextByte (asg_lfsr16_t *asg)
Get the next byte in the ASG16 pseudo random binary sequence.
uint8_t asg_lfsr32_cGetNextByte (asg_lfsr32_t *asg)
Get the next byte in the ASG32 pseudo random binary sequence.
uint8_t asg_lfsr64_cGetNextByte (asg_lfsr64_t *asg)
Get the next byte in the ASG64 pseudo random binary sequence.
Alternating Step Generator Get Next Bit Functions
Get the next bit in the Alternating Step Generator's pseudo random binary sequence. This is the functional core of the ASG implementation.
int asg_lfsr16_bGetNextBit (asg_lfsr16_t *asg)
Get the next bit in the ASG16 pseudo random binary sequence.
int asg_lfsr32_bGetNextBit (asg_lfsr32_t *asg)
Get the next bit in the ASG32 pseudo random binary sequence.
int asg_lfsr64_bGetNextBit (asg_lfsr64_t *asg)
Get the next bit in the ASG64 pseudo random binary sequence.
Detailed Description
Interface and usage of the alternating step prbs generator.
This file provides a Alternating Step Generator based on the Linear Feedback Shift Register generator for generating psuedo random bit sequences.
While this is not cryptographically secure either, it is probably good enough for relatively non-critical random number generation. It produces a reasonably good pseduo-random bit stream at a considerably lower cost than other 'better' bit stream generation alogrithms.
See also
asg.c
Definition in file asg.h.
Function Documentation
asg_lfsr16_bGetNextBit()
int asg_lfsr16_bGetNextBit (asg_lfsr16_t * asg)
Get the next bit in the ASG16 pseudo random binary sequence.
Parameters
asg Pointer to the asg_lfsr16_t structure.
Returns
The next bit in the sequence.
Definition at line 105 of file asg.c.
References ASG_LFSR16_t::a, ASG_LFSR16_t::b, ASG_LFSR16_t::c, and lfsr16_bGetNextBit().
Referenced by asg_lfsr16_cGetNextByte().
asg_lfsr16_cGetNextByte()
uint8_t asg_lfsr16_cGetNextByte (asg_lfsr16_t * asg)
Get the next byte in the ASG16 pseudo random binary sequence.
Parameters
asg Pointer to the asg_lfsr16_t structure.
Returns
The next byte in the sequence.
Definition at line 74 of file asg.c.
References asg_lfsr16_bGetNextBit().
asg_lfsr16_vAddEntropy()
void asg_lfsr16_vAddEntropy (asg_lfsr16_t * asg, void * entropy)
Add entropy to a asg_lfsr16_t structure.
Parameters
asg Pointer to the asg_lfsr16_t structure.
entropy buffer containing the atleast 6 bytes of entropy
Definition at line 55 of file asg.c.
References ASG_LFSR16_t::a, ASG_LFSR16_t::b, ASG_LFSR16_t::c, and lfsr16_vAddEntropy().
asg_lfsr16_vInit()
void asg_lfsr16_vInit (asg_lfsr16_t * asg)
Initialize a asg_lfsr16_t structure using the default seeds.
Parameters
asg Pointer to the asg_lfsr16_t structure to be initialized.
Definition at line 33 of file asg.c.
References ASG_LFSR16_t::a, ASG_LFSR16_t::b, ASG_LFSR16_t::c, and lfsr16_vInit().
asg_lfsr32_bGetNextBit()
int asg_lfsr32_bGetNextBit (asg_lfsr32_t * asg)
Get the next bit in the ASG32 pseudo random binary sequence.
Parameters
asg Pointer to the asg_lfsr32_t structure.
Returns
The next bit in the sequence.
Definition at line 116 of file asg.c.
References ASG_LFSR32_t::a, ASG_LFSR32_t::b, ASG_LFSR32_t::c, and lfsr32_bGetNextBit().
Referenced by asg_lfsr32_cGetNextByte().
asg_lfsr32_cGetNextByte()
uint8_t asg_lfsr32_cGetNextByte (asg_lfsr32_t * asg)
Get the next byte in the ASG32 pseudo random binary sequence.
Parameters
asg Pointer to the asg_lfsr32_t structure.
Returns
The next byte in the sequence.
Definition at line 84 of file asg.c.
References asg_lfsr32_bGetNextBit().
asg_lfsr32_vAddEntropy()
void asg_lfsr32_vAddEntropy (asg_lfsr32_t * asg, void * entropy)
Add entropy to a asg_lfsr32_t structure.
Parameters
asg Pointer to the asg_lfsr32_t structure.
entropy buffer containing the atleast 12 bytes of entropy
Definition at line 61 of file asg.c.
References ASG_LFSR32_t::a, ASG_LFSR32_t::b, ASG_LFSR32_t::c, and lfsr32_vAddEntropy().
asg_lfsr32_vInit()
void asg_lfsr32_vInit (asg_lfsr32_t * asg)
Initialize a asg_lfsr32_t structure using the default seeds.
Parameters
asg Pointer to the asg_lfsr32_t structure to be initialized.
Definition at line 40 of file asg.c.
References ASG_LFSR32_t::a, ASG_LFSR32_t::b, ASG_LFSR32_t::c, and lfsr32_vInit().
asg_lfsr64_bGetNextBit()
int asg_lfsr64_bGetNextBit (asg_lfsr64_t * asg)
Get the next bit in the ASG64 pseudo random binary sequence.
Parameters
asg Pointer to the asg_lfsr64_t structure.
Returns
The next bit in the sequence.
Definition at line 127 of file asg.c.
References ASG_LFSR64_t::a, ASG_LFSR64_t::b, ASG_LFSR64_t::c, and lfsr64_bGetNextBit().
Referenced by asg_lfsr64_cGetNextByte().
asg_lfsr64_cGetNextByte()
uint8_t asg_lfsr64_cGetNextByte (asg_lfsr64_t * asg)
Get the next byte in the ASG64 pseudo random binary sequence.
Parameters
asg Pointer to the asg_lfsr64_t structure.
Returns
The next byte in the sequence.
Definition at line 94 of file asg.c.
References asg_lfsr64_bGetNextBit().
asg_lfsr64_vAddEntropy()
void asg_lfsr64_vAddEntropy (asg_lfsr64_t * asg, void * entropy)
Add entropy to a asg_lfsr64_t structure.
Parameters
asg Pointer to the asg_lfsr64_t structure.
entropy buffer containing the atleast 24 bytes of entropy
Definition at line 67 of file asg.c.
References ASG_LFSR64_t::a, ASG_LFSR64_t::b, ASG_LFSR64_t::c, and lfsr64_vAddEntropy().
asg_lfsr64_vInit()
void asg_lfsr64_vInit (asg_lfsr64_t * asg)
Initialize a asg_lfsr64_t structure using the default seeds.
Parameters
asg Pointer to the asg_lfsr64_t structure to be initialized.
Definition at line 47 of file asg.c.
References ASG_LFSR64_t::a, ASG_LFSR64_t::b, ASG_LFSR64_t::c, and lfsr64_vInit().