ebs-prbs: prbs/lfsr.c File Reference
lfsr.c File Reference
Implementation of the lfsr prbs generator.
#include "lfsr.h"
Functions
void lfsr16_vInit (lfsr16_t *lfsrp)
Initialize a lfsr16_t using the default seed, LFSR16_SEED.
void lfsr32_vInit (lfsr32_t *lfsrp)
Initialize a lfsr32_t structure using the default seed, LFSR32_SEED.
void lfsr64_vInit (lfsr64_t *lfsrp)
Initialize a lfsr64_t structure using the default seed, LFSR64_SEED.
void lfsr16_vAddEntropy (lfsr16_t *lfsrp, void *entropy)
Add entropy to a lfsr16_t structure.
void lfsr32_vAddEntropy (lfsr32_t *lfsrp, void *entropy)
Add entropy to a lfsr32_t structure.
void lfsr64_vAddEntropy (lfsr64_t *lfsrp, void *entropy)
Add entropy to a lfsr64_t structure.
uint8_t lfsr16_cGetNextByte (lfsr16_t *lfsrp)
Get the next byte in the LFSR16 pseudo random binary sequence.
uint8_t lfsr32_cGetNextByte (lfsr32_t *lfsrp)
Get the next byte in the LFSR32 pseudo random binary sequence.
uint8_t lfsr64_cGetNextByte (lfsr64_t *lfsrp)
Get the next byte in the LFSR64 pseudo random binary sequence.
int lfsr16_bGetNextBit (lfsr16_t *lfsrp)
Get the next bit in the LFSR16 pseudo random binary sequence.
int lfsr32_bGetNextBit (lfsr32_t *lfsrp)
Get the next bit in the LFSR32 pseudo random binary sequence.
int lfsr64_bGetNextBit (lfsr64_t *lfsrp)
Get the next bit in the LFSR64 pseudo random binary sequence.
Detailed Description
Implementation of the lfsr prbs generator.
See lfsr.h for usage documentation. Implementation documentation should be added to this file as some point.
Definition in file lfsr.c.
Function Documentation
lfsr16_bGetNextBit()
int lfsr16_bGetNextBit (lfsr16_t * lfsrp)
Get the next bit in the LFSR16 pseudo random binary sequence.
Parameters
lfsrp Pointer to the lfsr16_t.
Returns
The next bit in the sequence.
Definition at line 91 of file lfsr.c.
Referenced by asg_lfsr16_bGetNextBit(), lfsr16_cGetNextByte(), and sg_lfsr16_bGetNextBit().
lfsr16_cGetNextByte()
uint8_t lfsr16_cGetNextByte (lfsr16_t * lfsrp)
Get the next byte in the LFSR16 pseudo random binary sequence.
Parameters
lfsrp Pointer to the lfsr16_t.
Returns
The next byte in the sequence.
Definition at line 60 of file lfsr.c.
References lfsr16_bGetNextBit().
lfsr16_vAddEntropy()
void lfsr16_vAddEntropy (lfsr16_t * lfsrp, void * entropy)
Add entropy to a lfsr16_t structure.
Parameters
lfsrp Pointer to the lfsr16_t.
entropy buffer containing the atleast 2 bytes of entropy.
Definition at line 47 of file lfsr.c.
Referenced by asg_lfsr16_vAddEntropy(), and sg_lfsr16_vAddEntropy().
lfsr16_vInit()
void lfsr16_vInit (lfsr16_t * lfsrp)
Initialize a lfsr16_t using the default seed, LFSR16_SEED.
Parameters
lfsrp Pointer to the lfsr16_t to be initialized.
Definition at line 34 of file lfsr.c.
Referenced by asg_lfsr16_vInit(), and sg_lfsr16_vInit().
lfsr32_bGetNextBit()
int lfsr32_bGetNextBit (lfsr32_t * lfsrp)
Get the next bit in the LFSR32 pseudo random binary sequence.
Parameters
lfsrp Pointer to the lfsr32_t.
Returns
The next bit in the sequence.
Definition at line 100 of file lfsr.c.
Referenced by asg_lfsr32_bGetNextBit(), lfsr32_cGetNextByte(), and sg_lfsr32_bGetNextBit().
lfsr32_cGetNextByte()
uint8_t lfsr32_cGetNextByte (lfsr32_t * lfsrp)
Get the next byte in the LFSR32 pseudo random binary sequence.
Parameters
lfsrp Pointer to the lfsr32_t.
Returns
The next byte in the sequence.
Definition at line 70 of file lfsr.c.
References lfsr32_bGetNextBit().
lfsr32_vAddEntropy()
void lfsr32_vAddEntropy (lfsr32_t * lfsrp, void * entropy)
Add entropy to a lfsr32_t structure.
Parameters
lfsrp Pointer to the lfsr32_t.
entropy buffer containing the atleast 4 bytes of entropy.
Definition at line 51 of file lfsr.c.
Referenced by asg_lfsr32_vAddEntropy(), and sg_lfsr32_vAddEntropy().
lfsr32_vInit()
void lfsr32_vInit (lfsr32_t * lfsrp)
Initialize a lfsr32_t structure using the default seed, LFSR32_SEED.
Parameters
lfsrp Pointer to the lfsr32_t to be initialized.
Definition at line 38 of file lfsr.c.
Referenced by asg_lfsr32_vInit(), and sg_lfsr32_vInit().
lfsr64_bGetNextBit()
int lfsr64_bGetNextBit (lfsr64_t * lfsrp)
Get the next bit in the LFSR64 pseudo random binary sequence.
Parameters
lfsrp Pointer to the lfsr64_t.
Returns
The next bit in the sequence.
Definition at line 109 of file lfsr.c.
Referenced by asg_lfsr64_bGetNextBit(), lfsr64_cGetNextByte(), and sg_lfsr64_bGetNextBit().
lfsr64_cGetNextByte()
uint8_t lfsr64_cGetNextByte (lfsr64_t * lfsrp)
Get the next byte in the LFSR64 pseudo random binary sequence.
Parameters
lfsrp Pointer to the lfsr64_t.
Returns
The next byte in the sequence.
Definition at line 80 of file lfsr.c.
References lfsr64_bGetNextBit().
lfsr64_vAddEntropy()
void lfsr64_vAddEntropy (lfsr64_t * lfsrp, void * entropy)
Add entropy to a lfsr64_t structure.
Parameters
lfsrp Pointer to the lfsr64_t.
entropy buffer containing the atleast 8 bytes of entropy.
Definition at line 55 of file lfsr.c.
Referenced by asg_lfsr64_vAddEntropy(), and sg_lfsr64_vAddEntropy().
lfsr64_vInit()
void lfsr64_vInit (lfsr64_t * lfsrp)
Initialize a lfsr64_t structure using the default seed, LFSR64_SEED.
Parameters
lfsrp Pointer to the lfsr64_t to be initialized.
Definition at line 42 of file lfsr.c.
Referenced by asg_lfsr64_vInit(), and sg_lfsr64_vInit().