ebs-prbs: prbs/lfsr.h File Reference
lfsr.h File Reference
Interface and usage of the lfsr prbs generator.
#include <stdint.h>
Macros
LFSR Taps and default seeds
These definitions specify the taps used by each of the LFSRs and provide default seeds. The default taps cannot be changed at run time or link time. The default seeds may be used by the application as per its requirements.
#define LFSR16_SEED 0xACE1
#define LFSR16_TAPS 0xD008
#define LFSR32_SEED 0xDEADACE1
#define LFSR32_TAPS 0x80200003
#define LFSR64_SEED 0x12345678DEADACE1
#define LFSR64_TAPS 0xD800000000000000
Typedefs
LFSR Typedefs
The core of the LFSR implementation is made of integers of appropriate sizes, representing a Linear Feedback Shift Register of as many bits as compose the integer. The value should not be used directly, the functions listed in the interface can be used to operate on the LFSR.
The LFSR implemented is a binary Galois LFSR.
typedef uint16_t lfsr16_t
16 bit LFSR typedef
typedef uint32_t lfsr32_t
32 bit LFSR typedef
typedef uint64_t lfsr64_t
64 bit LFSR typedef
Functions
LFSR Initialization Functions
Intialize the LFSRs with the default seed. These functions are superceded by the AddEntropy functions, and is retained here for backwards compatibility.
Applications should avoid using these.
void lfsr16_vInit (lfsr16_t *lfsrp)
Initialize a lfsr16_t using the default seed, LFSR16_SEED.
void lfsr32_vInit (lfsr32_t *lfsrp)
Initialize a lfsr32_t structure using the default seed, LFSR32_SEED.
void lfsr64_vInit (lfsr64_t *lfsrp)
Initialize a lfsr64_t structure using the default seed, LFSR64_SEED.
LFSR Add Entropy Functions
Add entropy to the LFSR. These functions simply replaces the LFSR with the provided entropy bytes. With the deprecation of the LFSR Initialization functions, applications must call this function and provide some entropy before the LFSR is usable.
If randomness is required, entropy should come from a random source. If determinism is required, the default seed or another predetermined constant may be used.
void lfsr16_vAddEntropy (lfsr16_t *lfsrp, void *entropy)
Add entropy to a lfsr16_t structure.
void lfsr32_vAddEntropy (lfsr32_t *lfsrp, void *entropy)
Add entropy to a lfsr32_t structure.
void lfsr64_vAddEntropy (lfsr64_t *lfsrp, void *entropy)
Add entropy to a lfsr64_t structure.
LFSR Get Next Byte Functions
Get the next byte in the LFSR pseudo random binary sequence. This function constructs the byte by repeatedly calling the bit generation functions.
uint8_t lfsr16_cGetNextByte (lfsr16_t *lfsrp)
Get the next byte in the LFSR16 pseudo random binary sequence.
uint8_t lfsr32_cGetNextByte (lfsr32_t *lfsrp)
Get the next byte in the LFSR32 pseudo random binary sequence.
uint8_t lfsr64_cGetNextByte (lfsr64_t *lfsrp)
Get the next byte in the LFSR64 pseudo random binary sequence.
LFSR Get Next Bit Functions
Get the next bit in the LFSR pseudo random binary sequence. This is the functional core of the LFSR implementation.
int lfsr16_bGetNextBit (lfsr16_t *lfsrp)
Get the next bit in the LFSR16 pseudo random binary sequence.
int lfsr32_bGetNextBit (lfsr32_t *lfsrp)
Get the next bit in the LFSR32 pseudo random binary sequence.
int lfsr64_bGetNextBit (lfsr64_t *lfsrp)
Get the next bit in the LFSR64 pseudo random binary sequence.
Detailed Description
Interface and usage of the lfsr prbs generator.
This file provides the Linear Feedback Shift Register generator for psuedo random bit sequences. It is intended for use in BER and protocol tests and should not be considered crytptographically secure.
An alternating step generator or shrinking generator can be constructed of these LFSRs which have relatively better cryptographic properties. Implementations of the SG and ASG based on the LFSR presented here are included in the library and can be found in sg.h and asg.h.
This library uses hardcoded polynomials for performace reasons. Polynomials need to be primitive and cannot be generated from entropy in any case. Primitive polynomials from Xilinx application note XAPP052 are used by default, this can be changed only by changing the preprocessor definitions in this file. If multiple LFSRs are instantiated, they will all use the same polynomials. While non-ideal, this is not as bad as it sounds. Any reasonable polynomial which works with randomly generated seeds will have exactly the same period anyway. The LFSR's seed can be set to a different value using the AddEntropy function.
See also
https://www.xilinx.com/support/documentation/application_notes/xapp052.pdf
Definition in file lfsr.h.
Function Documentation
lfsr16_bGetNextBit()
int lfsr16_bGetNextBit (lfsr16_t * lfsrp)
Get the next bit in the LFSR16 pseudo random binary sequence.
Parameters
lfsrp Pointer to the lfsr16_t.
Returns
The next bit in the sequence.
Definition at line 91 of file lfsr.c.
Referenced by asg_lfsr16_bGetNextBit(), lfsr16_cGetNextByte(), and sg_lfsr16_bGetNextBit().
lfsr16_cGetNextByte()
uint8_t lfsr16_cGetNextByte (lfsr16_t * lfsrp)
Get the next byte in the LFSR16 pseudo random binary sequence.
Parameters
lfsrp Pointer to the lfsr16_t.
Returns
The next byte in the sequence.
Definition at line 60 of file lfsr.c.
References lfsr16_bGetNextBit().
lfsr16_vAddEntropy()
void lfsr16_vAddEntropy (lfsr16_t * lfsrp, void * entropy)
Add entropy to a lfsr16_t structure.
Parameters
lfsrp Pointer to the lfsr16_t.
entropy buffer containing the atleast 2 bytes of entropy.
Definition at line 47 of file lfsr.c.
Referenced by asg_lfsr16_vAddEntropy(), and sg_lfsr16_vAddEntropy().
lfsr16_vInit()
void lfsr16_vInit (lfsr16_t * lfsrp)
Initialize a lfsr16_t using the default seed, LFSR16_SEED.
Parameters
lfsrp Pointer to the lfsr16_t to be initialized.
Definition at line 34 of file lfsr.c.
Referenced by asg_lfsr16_vInit(), and sg_lfsr16_vInit().
lfsr32_bGetNextBit()
int lfsr32_bGetNextBit (lfsr32_t * lfsrp)
Get the next bit in the LFSR32 pseudo random binary sequence.
Parameters
lfsrp Pointer to the lfsr32_t.
Returns
The next bit in the sequence.
Definition at line 100 of file lfsr.c.
Referenced by asg_lfsr32_bGetNextBit(), lfsr32_cGetNextByte(), and sg_lfsr32_bGetNextBit().
lfsr32_cGetNextByte()
uint8_t lfsr32_cGetNextByte (lfsr32_t * lfsrp)
Get the next byte in the LFSR32 pseudo random binary sequence.
Parameters
lfsrp Pointer to the lfsr32_t.
Returns
The next byte in the sequence.
Definition at line 70 of file lfsr.c.
References lfsr32_bGetNextBit().
lfsr32_vAddEntropy()
void lfsr32_vAddEntropy (lfsr32_t * lfsrp, void * entropy)
Add entropy to a lfsr32_t structure.
Parameters
lfsrp Pointer to the lfsr32_t.
entropy buffer containing the atleast 4 bytes of entropy.
Definition at line 51 of file lfsr.c.
Referenced by asg_lfsr32_vAddEntropy(), and sg_lfsr32_vAddEntropy().
lfsr32_vInit()
void lfsr32_vInit (lfsr32_t * lfsrp)
Initialize a lfsr32_t structure using the default seed, LFSR32_SEED.
Parameters
lfsrp Pointer to the lfsr32_t to be initialized.
Definition at line 38 of file lfsr.c.
Referenced by asg_lfsr32_vInit(), and sg_lfsr32_vInit().
lfsr64_bGetNextBit()
int lfsr64_bGetNextBit (lfsr64_t * lfsrp)
Get the next bit in the LFSR64 pseudo random binary sequence.
Parameters
lfsrp Pointer to the lfsr64_t.
Returns
The next bit in the sequence.
Definition at line 109 of file lfsr.c.
Referenced by asg_lfsr64_bGetNextBit(), lfsr64_cGetNextByte(), and sg_lfsr64_bGetNextBit().
lfsr64_cGetNextByte()
uint8_t lfsr64_cGetNextByte (lfsr64_t * lfsrp)
Get the next byte in the LFSR64 pseudo random binary sequence.
Parameters
lfsrp Pointer to the lfsr64_t.
Returns
The next byte in the sequence.
Definition at line 80 of file lfsr.c.
References lfsr64_bGetNextBit().
lfsr64_vAddEntropy()
void lfsr64_vAddEntropy (lfsr64_t * lfsrp, void * entropy)
Add entropy to a lfsr64_t structure.
Parameters
lfsrp Pointer to the lfsr64_t.
entropy buffer containing the atleast 8 bytes of entropy.
Definition at line 55 of file lfsr.c.
Referenced by asg_lfsr64_vAddEntropy(), and sg_lfsr64_vAddEntropy().
lfsr64_vInit()
void lfsr64_vInit (lfsr64_t * lfsrp)
Initialize a lfsr64_t structure using the default seed, LFSR64_SEED.
Parameters
lfsrp Pointer to the lfsr64_t to be initialized.
Definition at line 42 of file lfsr.c.
Referenced by asg_lfsr64_vInit(), and sg_lfsr64_vInit().