ebs-prbs: prbs/sg.h File Reference
sg.h File Reference
Interface and usage of the shrinking prbs generator.
#include "lfsr.h"
Data Structures
struct SG_LFSR16_t
16 bit LFSR based Shrinking Generator
struct SG_LFSR32_t
32 bit LFSR based Shrinking Generator
struct SG_LFSR64_t
64 bit LFSR based Shrinking Generator
Typedefs
Shrinking Generator Typedefs
These types contain the core of Shrinking Generators. Each is composed of two LFSRs of appropriate sizes.
Values in the struct should not be used directly. The functions listed in the interface can be used to operate on the SG.
typedef struct SG_LFSR16_t sg_lfsr16_t
16 bit LFSR based Shrinking Generator
typedef struct SG_LFSR32_t sg_lfsr32_t
32 bit LFSR based Shrinking Generator
typedef struct SG_LFSR64_t sg_lfsr64_t
64 bit LFSR based Shrinking Generator
Functions
Shrinking Generator Initialization Functions
Intialize the shrinking generator's LFSRs with the default seed. These functions are superceded by the AddEntropy functions, and is retained here for backwards compatibility.
Applications should avoid using these.
void sg_lfsr16_vInit (sg_lfsr16_t *sg)
Initialize a sg_lfsr16_t structure using the default seeds.
void sg_lfsr32_vInit (sg_lfsr32_t *sg)
Initialize a sg_lfsr32_t structure using the default seeds.
void sg_lfsr64_vInit (sg_lfsr64_t *sg)
Initialize a sg_lfsr64_t structure using the default seeds.
Shrinking Generator Add Entropy Functions
Add entropy to the shrinking gnerator. These functions simply replaces the contained LFSRs with the provided entropy bytes. With the deprecation of the SG Initialization functions, applications must call this function and provide some entropy before the SG is usable.
If randomness is required, entropy should come from a random source. If determinism is required, the default seed or another predetermined constant may be used.
void sg_lfsr16_vAddEntropy (sg_lfsr16_t *sg, void *entropy)
Add entropy to a sg_lfsr16_t structure.
void sg_lfsr32_vAddEntropy (sg_lfsr32_t *sg, void *entropy)
Add entropy to a sg_lfsr32_t structure.
void sg_lfsr64_vAddEntropy (sg_lfsr64_t *sg, void *entropy)
Add entropy to a sg_lfsr64_t structure.
Shrinking Generator Get Next Byte Functions
Get the next byte in the Shrinking Generator's pseudo random binary sequence. This function constructs the byte by repeatedly calling the bit generation functions.
uint8_t sg_lfsr16_cGetNextByte (sg_lfsr16_t *sg)
Get the next byte in the SG16 pseudo random binary sequence.
uint8_t sg_lfsr32_cGetNextByte (sg_lfsr32_t *sg)
Get the next byte in the SG32 pseudo random binary sequence.
uint8_t sg_lfsr64_cGetNextByte (sg_lfsr64_t *sg)
Get the next byte in the SG64 pseudo random binary sequence.
Shrinking Generator Get Next Bit Functions
Get the next bit in the Shrinking Generator's pseudo random binary sequence. This is the functional core of the SG implementation.
int sg_lfsr16_bGetNextBit (sg_lfsr16_t *sg)
Get the next bit in the SG16 pseudo random binary sequence.
int sg_lfsr32_bGetNextBit (sg_lfsr32_t *sg)
Get the next bit in the SG32 pseudo random binary sequence.
int sg_lfsr64_bGetNextBit (sg_lfsr64_t *sg)
Get the next bit in the SG64 pseudo random binary sequence.
Detailed Description
Interface and usage of the shrinking prbs generator.
This file provides a Shrinking Generator based on the Linear Feedback Shift Register generator for generating psuedo random bit sequences.
See also
sg.c
Definition in file sg.h.
Function Documentation
sg_lfsr16_bGetNextBit()
int sg_lfsr16_bGetNextBit (sg_lfsr16_t * sg)
Get the next bit in the SG16 pseudo random binary sequence.
Parameters
sg Pointer to the sg_lfsr16_t structure.
Returns
The next bit in the sequence.
Definition at line 99 of file sg.c.
References SG_LFSR16_t::a, SG_LFSR16_t::b, and lfsr16_bGetNextBit().
Referenced by sg_lfsr16_cGetNextByte().
sg_lfsr16_cGetNextByte()
uint8_t sg_lfsr16_cGetNextByte (sg_lfsr16_t * sg)
Get the next byte in the SG16 pseudo random binary sequence.
Parameters
sg Pointer to the sg_lfsr16_t structure.
Returns
The next byte in the sequence.
Definition at line 68 of file sg.c.
References sg_lfsr16_bGetNextBit().
sg_lfsr16_vAddEntropy()
void sg_lfsr16_vAddEntropy (sg_lfsr16_t * sg, void * entropy)
Add entropy to a sg_lfsr16_t structure.
Parameters
sg Pointer to the sg_lfsr16_t structure.
entropy buffer containing the atleast 4 bytes of entropy
Definition at line 52 of file sg.c.
References SG_LFSR16_t::a, SG_LFSR16_t::b, and lfsr16_vAddEntropy().
sg_lfsr16_vInit()
void sg_lfsr16_vInit (sg_lfsr16_t * sg)
Initialize a sg_lfsr16_t structure using the default seeds.
Parameters
sg Pointer to the sg_lfsr16_t structure to be initialized.
Definition at line 33 of file sg.c.
References SG_LFSR16_t::a, SG_LFSR16_t::b, and lfsr16_vInit().
sg_lfsr32_bGetNextBit()
int sg_lfsr32_bGetNextBit (sg_lfsr32_t * sg)
Get the next bit in the SG32 pseudo random binary sequence.
Parameters
sg Pointer to the sg_lfsr32_t structure.
Returns
The next bit in the sequence.
Definition at line 110 of file sg.c.
References SG_LFSR32_t::a, SG_LFSR32_t::b, and lfsr32_bGetNextBit().
Referenced by sg_lfsr32_cGetNextByte().
sg_lfsr32_cGetNextByte()
uint8_t sg_lfsr32_cGetNextByte (sg_lfsr32_t * sg)
Get the next byte in the SG32 pseudo random binary sequence.
Parameters
sg Pointer to the sg_lfsr32_t structure.
Returns
The next byte in the sequence.
Definition at line 78 of file sg.c.
References sg_lfsr32_bGetNextBit().
sg_lfsr32_vAddEntropy()
void sg_lfsr32_vAddEntropy (sg_lfsr32_t * sg, void * entropy)
Add entropy to a sg_lfsr32_t structure.
Parameters
sg Pointer to the sg_lfsr32_t structure.
entropy buffer containing the atleast 8 bytes of entropy
Definition at line 57 of file sg.c.
References SG_LFSR32_t::a, SG_LFSR32_t::b, and lfsr32_vAddEntropy().
sg_lfsr32_vInit()
void sg_lfsr32_vInit (sg_lfsr32_t * sg)
Initialize a sg_lfsr32_t structure using the default seeds.
Parameters
sg Pointer to the sg_lfsr32_t structure to be initialized.
Definition at line 39 of file sg.c.
References SG_LFSR32_t::a, SG_LFSR32_t::b, and lfsr32_vInit().
sg_lfsr64_bGetNextBit()
int sg_lfsr64_bGetNextBit (sg_lfsr64_t * sg)
Get the next bit in the SG64 pseudo random binary sequence.
Parameters
sg Pointer to the sg_lfsr64_t structure.
Returns
The next bit in the sequence.
Definition at line 121 of file sg.c.
References SG_LFSR64_t::a, SG_LFSR64_t::b, and lfsr64_bGetNextBit().
Referenced by sg_lfsr64_cGetNextByte().
sg_lfsr64_cGetNextByte()
uint8_t sg_lfsr64_cGetNextByte (sg_lfsr64_t * sg)
Get the next byte in the SG64 pseudo random binary sequence.
Parameters
sg Pointer to the sg_lfsr64_t structure.
Returns
The next byte in the sequence.
Definition at line 88 of file sg.c.
References sg_lfsr64_bGetNextBit().
sg_lfsr64_vAddEntropy()
void sg_lfsr64_vAddEntropy (sg_lfsr64_t * sg, void * entropy)
Add entropy to a sg_lfsr64_t structure.
Parameters
sg Pointer to the sg_lfsr64_t structure.
entropy buffer containing the atleast 8 bytes of entropy
Definition at line 62 of file sg.c.
References SG_LFSR64_t::a, SG_LFSR64_t::b, and lfsr64_vAddEntropy().
sg_lfsr64_vInit()
void sg_lfsr64_vInit (sg_lfsr64_t * sg)
Initialize a sg_lfsr64_t structure using the default seeds.
Parameters
sg Pointer to the sg_lfsr64_t structure to be initialized.
Definition at line 45 of file sg.c.
References SG_LFSR64_t::a, SG_LFSR64_t::b, and lfsr64_vInit().